---
# fetch OULibraries.centos7 from github
- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: OULibraries.centos7
# fetch OULibraries.fedora4 from github
- src: https://github.com/OULibraries/ansible-role-fedora4
  version: master
  name: OULibraries.fedora4
# fetch OULibraries.ngrok from github
- src: https://github.com/OULibraries/ansible-role-ngrok
  version: master
  name: OULibraries.ngrok
